version: '3'

services:

  fuelphp-app:
    container_name: fuelphp-app
    build: ./docker
    volumes:
      - "./php:/var/www/html/php"
      - "./app:/var/www/html/app"
    ports:
      - 8000:80
